name: BiomeChange
version: 1.0
main: me.tiger.biomeChange.BiomeChange
api-version: "1.20"
commands:
  biomechange:
    description: Enable or disable biome switching
    usage: /biomechange <enable|disable>
    permission: biomechange.use
permissions:
  biomechange.use:
    default: op